# Generated by Django 5.0.2 on 2024-02-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregables',
            new_name='Entregable',
        ),
    ]
