# Generated by Django 5.0.2 on 2024-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_entregables_entregable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
